URI: file://data/projects/lu_cn_analyzer_cr/ZABAGED202412.gdb

# This list contains buffer options, values in controlling_atr_name change length of buffers for point/line objects. Distance is in meters.
buffer_layers:
  - input_layer_name: "SilniceDalnice"
    controlling_atr_name: "typsil_k"
    buffer_levels:
      - priority: "1"
        values: ["D1", "D2", "M", "D1p", "Mp", "Mv"]
        distance: 15
      - priority: "2"
        values: ["S1", "S1v", "S1p"]
        distance: 5.5
      - priority: "3"
        values: ["S2", "S3", "D2p", "S2p", "S2v", "S3p", "S3v"]
        distance: 5
    default_buffer: 4.5

  - input_layer_name: "OsaLetistniDrahy" # since buffering by random int in controlling_atr is not implemented yet, default_buffer is  20 wich is mean value of all of them and most common widths are also here
    controlling_atr_name: "sirka"
    buffer_levels:
      - priority: "1"
        values: [150]
        distance: 150
      - priority: "2"
        values: [100]
        distance: 100
      - priority: "3"
        values: [60]
        distance: 60
      - priority: "4"
        values: [40]
        distance: 40
      - priority: "5"
        values: [30]
        distance: 30
      - priority: "6"
        values: [40]
        distance: 40
    default_buffer: 20

  - input_layer_name: "SilniceNeevidovana"
    controlling_atr_name: "NaN"
    default_buffer: 2.5

  - input_layer_name: "Ulice"
    controlling_atr_name: "NaN"
    default_buffer: 3
    
  - input_layer_name: "LiniovaVegetace"
    controlling_atr_name: "NaN"
    default_buffer: 3
 
  - input_layer_name: "ZeleznicniTrat"
    controlling_atr_name: "NaN"
    default_buffer: 2.5

  - input_layer_name: "ZeleznicniVlecka"
    controlling_atr_name: "NaN"
    default_buffer: 2.5
    
# This list contains settings for ZABAGED layers where their LandUse code is updated by some value in its attribute.
# base_use_code is the LandUse code for the whole layer, and numbers from values in the controlling attribute are added to base_use_code.
layers:
  - name: "LesniPudaSeStromyKategorizovana"
    base_use_code: 30000
    controlling_attribute: "druh_k"
    value_increments:
      N: 0
      J: 3200 # jehlicnaty
      L: 3100 # listnaty
      S: 3300 # smiseny

  - name: "Heliport"
    base_use_code: 44100
    controlling_attribute: "povrfato_k"
    value_increments:
      Z: 0   # zpevněný (asfalt, beton)
      P: 100 # zpevněný (panel, dlažba)
      H: 100 # nedostatečně zpevněný (tráva, hlína, písek, kamení)
      S: 100 # smíšený (nejednotný povrch)

  - name: "OrnaPudaAOstatniDaleNespecifikovanePlochy"
    base_use_code: 10000  
    controlling_attribute: "typ_pudy_p"
    value_increments:
      OR: 0      # orna
      OSN: 34200 # ostatni

  - name: "Elektrarna"
    base_use_code: 44200
    controlling_attribute: "PODTYPEL_K"
    value_increments:
      "003": 0    # solární
      "001": 100  # vodní
      "008": 100  # parní
      "009": 100  # paroplynová
      "010": 100  # plynová a spalovací
      "011": 100  # vodní přečerpávací
      "012": 100  # ostatní alternativní

  - name: "RozvalinaZricenina"
    base_use_code: 44200
    controlling_attribute: "podtypob_k"
    value_increments:
      R: 0    # rozvalina
      Z: 100  # zricenina
      ZH: 100 # zricenina hradu
      ZZ: 100 # zricenina zamku
  - name: "ArealUceloveZastavby" # while selecting from INTRAVILAN/EXTRAVILAN temporary was selected the lower number (more water resilient Land Use code)
    base_use_code: 44100
    controlling_attribute: "typzast_k"
    value_increments:
      101: 100  # hlubinná těžba - bez omezení
      102: 0    # strojírenský průmysl - plocha ≥ 5 000 m2
      103: 0    # chemický průmysl - plocha ≥ 5 000 m2
      104: 0    # textilní, oděvní a kožedělný - plocha ≥ 5 000 m2
      105: 0    # průmysl skla, keramiky a stavebních hmot - plocha ≥ 5 000 m2
      106: 0    # potravinářský průmysl - plocha ≥ 5 000 m2
      107: 0    # dřevozpracující a papírenský průmysl - plocha ≥ 5 000 m2
      108: 0    # polygrafický průmysl - plocha ≥ 5 000 m2
      109: 0    # hutnický průmysl - plocha ≥ 5 000 m2
      110: 0    # ostatní, nerozlišený průmysl - plocha ≥ 5 000 m2
      111: 100  # chov hospodářských zvířat - plocha ≥ 5 000 m2
      112: 0    # zemědělský areál ostatní - plocha ≥ 5 000 m2
      113: 0    # skleníkové pěstování plodin - plocha ≥ 5 000 m2
      201: 100  # areál hradu (zřícenin) - bez omezení
      202: 100  # areál zámku - bez omezení
      203: 100  # archeologické naleziště - bez omezení
      204: 100  # hvězdárna - bez omezení
      205: 0    # kostel - bez omezení
      206: 100  # klášter - bez omezení
      207: 0    # kulturní objekt ostatní - bez omezení
      208: 0    # muzeum - bez omezení
      209: 100  # letní scéna - bez omezení
      210: 100  # škola - bez omezení
      211: 0    # výstaviště - plocha ≥ 10 000 m2
      212: 100  # skanzen - bez omezení
      213: 100  # zoo, safari - bez omezení
      214: 100  # botanická zahrada - bez omezení
      215: 100  # školské zařízení - bez omezení
      301: 100  # sportovní areál - plocha ≥ 2 000 m2
      302: 0    # plavecký areál - bez omezení
      303: 0    # stadión - bez omezení
      304: 100  # dostihový areál, parkur - bez omezení
      305: 100  # auto-moto-cyklo areál - bez omezení
      307: 100  # střelnice - bez omezení
      309: 0    # koupaliště - bez omezení
      310: 200  # camping - plocha ≥ 5 000 m2
      311: 100  # hřiště - plocha ≥ 2 000 m2
      312: 100  # chatová kolonie - plocha ≥ 10 000 m2 nebo šířka ≥ 50m a délka ≥ 200m
      313: 100  # rekreační zástavba - plocha ≥ 5 000 m2
      314: 100  # kynologické cvičiště - bez omezení
      315: 0    # zábavní park - bez omezení
      316: 100  # zahrádkářská osada - bez omezení
      401: 0    # sklad, hangár - plocha ≥ 5 000 m2
      402: 0    # přístav - bez omezení
      403: 100  # depo - bez omezení
      404: 0    # technické služby - bez omezení
      405: 100  # úpravna vody - bez omezení
      406: 100  # čistírna odpadních vod - bez omezení
      407: 0    # vodojem zemní - bez omezení
      408: 0    # autobusové nádraží - bez omezení
      409: 0    # čerpací stanice pohonných hmot - bez omezení
      410: 100  # meteorologická stanice - bez omezení
      411: 0    # vysílač - bez omezení
      412: 100  # nemocnice - bez omezení
      413: 100  # další zdravotní a sociální zařízení - bez omezení
      414: 0    # věznice - bez omezení
      415: 100  # kasárny a vojenské objekty - bez omezení
      416: 0    # skupinové garáže - plocha ≥ 2 000 m2
      417: 0    # hasičská stanice, zbrojnice - bez omezení
      418: 100  # policejní areál - bez omezení
      
      
  - name: "PovrchovaTezbaLom"
    base_use_code: 44100
    controlling_attribute: "DRUHTEZ_K"
    value_increments:
      7: 100    # uhlí
      13: 100   # cihlářská surovina
      16: 100   # kámen
      25: 200   # písek
      27: 100   # rudy, radioaktivní suroviny
      28: 200   # rašelina
      36: 200   # štěrkopísek
      37: 0     # keramické suroviny
      38: 100   # vápenec, dolomit
      39: 100   # ostatní nerudy
      −1: 100   # nezadáno/neznámo
      
  - name: "OsaLetistniDrahy"
    base_use_code: 22100
    controlling_attribute: "povrch_k"
    value_increments:
      N: 0     # nezpevněný
      Z: 22000 # zpevněný >> 44100

      
      
      
      
      

