# URL: https://mze.gov.cz/public/app/wms/plpis_wfs.fcgi
DATA_SOURCE: /home/martin/geodata/lpis_20250104.gdb
# LPIS WFS layer name with desired polygons.
# layer_name: LPIS_DPB_UCINNE
layer_name: lpis_20250104
# This list contains settings for LPIS layer where their LandUse code is updated by some value in its attribute.
# base_use_code is the LandUse code for the whole layer, and numbers from values in the controlling attribute are added to base_use_code.
layers:
  - name: "LPIS_layer"
    base_use_code: 10000
    controlling_attribute: "kultura"
    value_increments:
      "standartní orná půda": 100
      "chmelnice": 3100
      "vinice": 3200
      "ovocný sad": 40000
      "trvalý travní porost": 10000
      "travní porost (na orné půdě)": 10000
      "rybník": 67200
      "zalesněná půda": 20000
      "mimoprodukční plocha": 56400
      "jiná trvalá kultura": 3400
      "jiná kultura": 100
      "školka": 2100
      "plocha s kontejnery": 30000
      "rychle rostoucí dřeviny pěstované na výmladkových plantážích": 24100
      "plocha s víceletými produkčními plodinami": 3400
      "plocha s lanýži": 100

