land_use:
  - keywords: [Orná, orná, Orna, orna]
    code: 10000
  - keywords: [Travní, travní, Travni, travni]
    code: 20000
  - keywords: [Lesní, lesní, Lesni, lesni]
    code: 30000
  - keywords: [Křovinatým, křovinatým, Krovinatym, krovinatym]
    code: 33500
  - keywords: [Vodní_plocha, "Vodní plocha", vodní_plocha, "vodní plocha", Vodni_plocha, "Vodni plocha", vodni_plocha, "vodni plocha", "VodniPlocha"]
    code: 77200
  - keywords: [Vodní_tok, "Vodní tok", vodní_tok, "vodní tok", Vodni_tok, "Vodni tok", vodni_tok, "vodni tok", "VodniTok"]
    code: 77100
  - keywords: [Skalní, skalní, Skalni, skalni]
    code: 88200
  - keywords: [Budova, budova, budov, Budov]
    code: 44100
  - keywords: [Věž, věž, Vez, vez]
    code: 44100
  - keywords: [Nadrz, nadrz, Nádrž, nádrž]
    code: 44100
  - keywords: [Silo, silo]
    code: 44100
  - keywords: [Hrad , hrad ]
    code: 44100    
  - keywords: [Zamek, zamek, zámek, Zámek]
    code: 44100
  - keywords: [Tribuna, tribuna]
    code: 44100 
  - keywords: [Ulice, ulice]
    code: 44100 
  - keywords: [Pesina, pesina, pěšina, Pěšina]
    code: 44100 
  - keywords: [Parkoviste, parkoviste, parkoviště, Parkoviště]
    code: 44100 
  - keywords: [Trať, trať, trat, Trat]
    code: 44200 
  - keywords: [Kolejiste, kolejiště, kolejiste, Kolejiště]
    code: 44200 
  - keywords: [Zastavka, zastavka, zastávka, Zastávka]
    code: 44100 
  - keywords: [Silnice, slinice]
    code: 44100 
  - keywords: [Chmelnice, chmelnice]
    code: 55100
  - keywords: [Vinice, vinice]
    code: 55100 
  - keywords: [Zahrada, zahrada]
    code: 42000 
  - keywords: [Vinice, vinice]
    code: 55100
  - keywords: [Rozvodna, rozvodna]
    code: 44300 
  - keywords: [Okrasna, okrasna, Okrasná, okrasná]
    code: 44200
  - keywords: [Hřbitov, Hrbitov, hrbitov, hřbitov]
    code: 44200
  - keywords: [Účel, účel, ucel, Ucel]
    code: 44100 
  - keywords: [Skládka, skladka, Skladka, skládka]
    code: 44100
  - keywords: [Zakrytý, zakryty, Zakryty, zakrytý]
    code: 44100
  - keywords: [Skleník, sklenik, Sklenik, skleník]
    code: 44100
  - keywords: [Bažina, bazina, Bazina, bažina]
    code: 66600
  - keywords: [Tezba, těžba, tezba, Těžba]
    code: 44100
  - keywords: [zřícenina, Zricenina, zricenina, Zřícenina]
    code: 44100   
  - keywords: [liniova, Liniova, Liniová, liniová]
    code: 66100   
  - keywords: [raseliniste, rašeliniště, Raseliniste, Rašeliniště]
    code: 66600   
  - keywords: [precerpavaci, přečerpávací, Precerpavaci, Přečerpávací]
    code: 44200   
  - keywords: [sucha, Sucha, suchá, Suchá]
    code: 22200  
  - keywords: [Kulna, kulna, kůlna, Kulna]
    code: 44100  
  - keywords: [Ostatni, ostanti, ostatní, Ostatní]
    code: 44200
  - keywords: [Těžba, tezba, Tezba, těžba]
    code: 44200
  - keywords: [Letiste, letiste, letiště, Letiště]
    code: 20000
  - keywords: [Tocna, tocna, točna, Točna]
    code: 44200
  - keywords: [Areál_železniční, Areal_zeleznicni, areál_železniční, areal_zeleznicni, "Areál železniční", "Areal zeleznicni", "areál železniční", "areal zeleznicni"]
    code: 44200
  - keywords: [sesuv, Sesuv]
    code: 44300
  - keywords: [Úložné, ulozne, úložné, Ulozne]
    code: 44300
  - keywords: [Bažina, bazina, bažina, Bazina]
    code: 66600
  - keywords: [Vlečka, vlecka, vlečka, Vlecka]
    code: 44200
